version: '3.8'

services:
  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    restart: always
    ports:
      - "3001:3001"

  posts:
    build:
      dockerfile: Dockerfile
      context: ./posts
    restart: always
    ports:
      - "3002:3002"

  comments:
    build:
      dockerfile: Dockerfile
      context: ./comments
    restart: always
    ports:
      - "3003:3003"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - users
      - posts
      - comments
