# route:
#   group_by: ['alertname']
#   group_wait: 30s
#   group_interval: 5m
#   repeat_interval: 1h
#   receiver: 'web.hook'
# receivers:
#   - name: 'web.hook'
#     webhook_configs:
#       - url: 'http://127.0.0.1:5001/'
# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']

route:
  receiver: admin

receivers:
  - name: admin
    email_configs:
      - to: "gouravgupta840@gmail.com"
        from: "example@gmail.com"
        smarthost: smtp.gmail.com:587
        auth_username: "example@gmail.com"
        auth_identity: "example@gmail.com"
        auth_password: "fqkvkumorgaqgkat"
